package com.adnre.spacegame.gui;

public enum EnumGui {
    // Main gui stuff
    GUI_SELECTED_ENTITY, GUI_HOTBAR_ITEM, GUI_TOOLTIP_ITEM, GUI_TOOLTIP_HOMESTAR, GUI_BUTTON_CLOSE_WINDOW,

    // Store stuff
    GUI_BUTTON_STORE_BUY, GUI_BUTTON_STORE_CLOSE, GUI_BUTTON_STORE_OPEN, GUI_STORE_BACKGROUND,

    // Pause screen stuff
    GUI_BUTTON_PAUSE_RESUME, GUI_BUTTON_PAUSE_SAVE, GUI_BUTTON_PAUSE_LOAD,

    // Spaceport screen stuff
    GUI_BUTTON_SPACEPORT_REFUEL, GUI_BUTTON_SPACEPORT_CLOSE, GUI_SPACEPORT_BACKGROUND,
}
